#pragma config(Sensor, port3,  estop,          sensorVexIQ_Touch)
#pragma config(Motor,  motor1,          left,          tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor2,          right,         tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
motor[motor1] = 63;
}
